version: "3"
services:
    postgres:
        image: postgres:12
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5432"]
            interval: 1s
            timeout: 20s
            retries: 20

    mongo:
        image: mongo
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DB}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongo-volume:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        restart: always
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test
            interval: 1s
            timeout: 20s
            retries: 20
    client:
        image: node:12
        privileged: true
        ports:
            - 0.0.0.0:80:80
        command: bash -c "echo 123 && cd app &&  npm i && npm run build && npm run serve"
        volumes:
            - .:/app
    backend:
        image: node:12
        environment:
            - PORT=${BACKEND_PORT}
            - POSTGRES_HOSTNAME=postgres
            - POSTGRES_PORT=${POSTGRES_PORT}
            - MONGO_HOSTNAME=mongo
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DB=${MONGO_DB}
        depends_on:
            - mongo
            - postgres
        privileged: true
        ports:
            - 0.0.0.0:${BACKEND_PORT}:${BACKEND_PORT}
        command: bash -c "cd app && npm install -g typescript && npm i && npm run buildback && npm run serveback"
        volumes:
            - .:/app



volumes:
    mongo-volume:
    node_modules:
    data-volume:
