version: "3"
services:
    postgres:
        image: postgres:12
        ports:
            - "5432:5432"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db
volumes:
    data-volume:
