name: Deploy

on:
    push:
      branches: [ feature-51, main ]
    pull_request:
      branches: [ main ]

jobs:
    build-heroku:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "zurichgame"
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  branch: "main"
                  usedocker: true

    build-yacloud:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.YACLOUD_SSH_PRIVATE }}
                name: id_rsa
                known_hosts: ${{ secrets.YACLOUD_KNOWN_HOST }}
                if_key_exists: replace
            - name: rsync over ssh
              run: rsync ./ $SSH_LOGIN@$SSH_IP:~/
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_LOGIN}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - name: run docker over ssh
              run: |
                ssh $SSH_LOGIN@$SSH_IP sudo docker-compose up -d
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_LOGIN}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - name: check status
              run: |
                sleep 5 \
                status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://$SSH_IP) \
                if [[ $status_code -ne 200 ]]; then echo Error; exit 1; fi
              env:
                SSH_IP: ${{secrets.YACLOUD_IP}}
