name: Deploy

on:
    push:
      branches: [ feature-51, main ]
    pull_request:
      branches: [ main ]

jobs:
    build-heroku:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "zurichgame"
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  branch: "main"
                  usedocker: true

    build-yacloud:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.YACLOUD_SSH_PRIVATE }}
                known_hosts: ${{ secrets.KNOWN_HOSTS }}
                if_key_exists: replace
            - name: rsync over ssh
              run: rsync ./ $SSH_LOGIN@$SSH_IP:~/
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_SSH_PRIVATE}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - run: ssh $SSH_LOGIN@SSH_IP sudo docker-compose up
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_SSH_PRIVATE}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
