name: Deploy

on:
    push:
      branches: [ feature-51, main ]
    pull_request:
      branches: [ main ]

jobs:
    build-heroku:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "zurichgame"
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  branch: "main"
                  usedocker: true

    build-yacloud:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - run: |
                sudo mkdir -p ~/.ssh/
                echo "$SSH_KEY" > key
                sudo chmod 600 key
                echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                SSH_KEY: ${{secrets.YACLOUD_SSH_PRIVATE}}
                SSH_KNOWN_HOSTS: ${{secrets.YACLOUD_KNOWN_HOST}}
            - run: rsync -av  -e "ssh -i key" ./ $SSH_LOGIN@$SSH_IP:~/
              shell: bash
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_SSH_PRIVATE}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - run: ssh $SSH_LOGIN@SSH_IP -i key sudo docker-compose up
