name: Deploy

on:
    push:
      branches: [ ssl, main ]
    pull_request:
      branches: [ main ]

jobs:
    build-heroku:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "zurichgame"
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  branch: "main"
                  usedocker: true

    build-yacloud:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.YACLOUD_SSH_PRIVATE }}
                name: id_rsa
                known_hosts: ${{ secrets.YACLOUD_KNOWN_HOST }}
                if_key_exists: replace
            - name: rsync over ssh
              run: rsync -avz --exclude nginx/ssl  --exclude nginx/ssl1 ./ $SSH_LOGIN@$SSH_IP:~/
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_LOGIN}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - name: run docker over ssh
              run: |
                ssh $SSH_LOGIN@$SSH_IP sudo docker-compose up -d
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_LOGIN}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - name: Check status code of production site
              uses: lakuapik/gh-actions-http-status@v1
              with:
                sites: '["${{secrets.YACLOUD_IP}}"]'
                expected: '[200]'
