name: Deploy

on:
    push:
      branches: [ feature-51, main ]
    pull_request:
      branches: [ main ]

jobs:
    build-heroku:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "zurichgame"
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
                  branch: "main"
                  usedocker: true

    build-yacloud:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - run: |
                mkdir -p ~/.ssh/
                echo "$SSH_KEY" > yakey
                chmod 600 yakey
                cat >>~/.ssh/config <<END
                Host deploy-yacloud
                    HostName $SSH_IP
                    User $SSH_LOGIN
                    IdentityFile yakey
                    StrictHostKeyChecking no
                END
              shell: bash
              env:
                SSH_KEY: ${{secrets.YACLOUD_SSH_PRIVATE}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
                SSH_LOGIN: ${{secrets.YACLOUD_SSH_PRIVATE}}
            - run: rsync  ./ deploy-yacloud:~/
              shell: bash
              env:
                SSH_LOGIN: ${{secrets.YACLOUD_SSH_PRIVATE}}
                SSH_IP: ${{secrets.YACLOUD_IP}}
            - run: ssh -i yakey sudo docker-compose up
